name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven (test 1)
      run: mvn -B package --file pom.xml
    - name: Build with Maven (test 2)
      run: mvn -B clean install
    - name: Build with Maven (test 3)
      run: mvn -B clean compile
    - name: Grant execute permission for buildjar
      run: chmod +x buildjar
    - name: Create JAR file
      run: ./buildjar
